### ISSUE TITLE
Potential Typo in Eq 12

### ISSUE THREAD

**Issue by DodoTheDeveloper** [krasserm/bayesian-machine-learning#11]
Greetings,

I think there might be a typo in equation 12, where the log of the posterior is calculated.

![image](https://user-images.githubusercontent.com/38818906/81509236-78dd9e00-9309-11ea-89c9-5bfe61e845c1.png)

In equation 6 there is a minus before E_D and it looks like it has been overlooked, when using the log prior in equation 12. 

![image](https://user-images.githubusercontent.com/38818906/81509175-12588000-9309-11ea-82f3-c0fe6482869f.png)

When trying to derivate the log posterior by using Bayes Theorem I almost got the same solution as in this article but was not able to find my error with the sign.

While reading Pattern Recognition and Machine Learning from Bishop(2006) I saw on page 153 equation 3.55 I found support of my theory that there might be a missing sign. 

I created a PR #12. If I'm wrong please just close the request and the PR.

**Comment by krasserm** [comment]
PR merged, thanks!
