### ISSUE TITLE
How to use your code for the dimensions of latent space which are larger than 2

### ISSUE THREAD

**Issue by xuzhang5788** [krasserm/bayesian-machine-learning#13]
Thank you so much for your great post. http://krasserm.github.io/2018/04/07/latent-space-optimization/.

In your post, you used MNIST dataset and encoded images into a latent space with dimension 2. If I want the dimension is larger than 2, how can I use your code? 

I want to replicate "chemical variational auto-encoder", but they didn't open their codes on the optimization parts. 

Your post is so great and clearly explained BO. Thank you so much.

**Comment by krasserm** [comment]
You can also use higher-dimensional spaces. See https://krasserm.github.io/2018/03/21/bayesian-optimization/ section "Hyperparameter tuning with Bayesian optimization" for an example.

**Comment by xuzhang5788** [comment]
Thank you so much for your reply. I read your recommended post, but I still couldn't get it. GpyOpt said if dimension is larger than 20, the results will be bad. In the paper of ChemVAE, the dimension of latent space is 196. Do you mean that I can treat these 196 numbers as hyperparameters and tuning them using Bayesian optimization? Many thanks.
