### ISSUE TITLE
ValueError in gaussian_processes.ipynb

### ISSUE THREAD

**Issue by Ethanwl** [krasserm/bayesian-machine-learning#15]
`res = minimize(nll_fn(X_train, Y_train, noise), [1, 1], 
               bounds=((1e-5, None), (1e-5, None)),
               method='L-BFGS-B')`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-956452f1583a> in <module>
     50 res = minimize(nll_fn(X_train, Y_train, noise), [1, 1], 
     51                bounds=((1e-5, None), (1e-5, None)),
---> 52                method='L-BFGS-B')
     53 
     54 # Store the optimization results in global variables so that we can

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    616     elif meth == 'l-bfgs-b':
    617         return _minimize_lbfgsb(fun, x0, args, jac, bounds,
--> 618                                 callback=callback, **options)
    619     elif meth == 'tnc':
    620         return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, finite_diff_rel_step, **unknown_options)
    306     sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
    307                                   bounds=new_bounds,
--> 308                                   finite_diff_rel_step=finite_diff_rel_step)
    309 
    310     func_and_grad = sf.fun_and_grad

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\optimize.py in _prepare_scalar_function(fun, x0, jac, args, bounds, epsilon, finite_diff_rel_step, hess)
    260     # calculation reduces overall function evaluations.
    261     sf = ScalarFunction(fun, x0, args, grad, hess,
--> 262                         finite_diff_rel_step, bounds, epsilon=epsilon)
    263 
    264     return sf

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\_differentiable_functions.py in __init__(self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon)
     93 
     94         self._update_grad_impl = update_grad
---> 95         self._update_grad()
     96 
     97         # Hessian Evaluation

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\_differentiable_functions.py in _update_grad(self)
    169     def _update_grad(self):
    170         if not self.g_updated:
--> 171             self._update_grad_impl()
    172             self.g_updated = True
    173 

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\_differentiable_functions.py in update_grad()
     90                 self.ngev += 1
     91                 self.g = approx_derivative(fun_wrapped, self.x, f0=self.f,
---> 92                                            **finite_diff_options)
     93 
     94         self._update_grad_impl = update_grad

~\Anaconda3\envs\tianshou\lib\site-packages\scipy\optimize\_numdiff.py in approx_derivative(fun, x0, method, rel_step, abs_step, f0, bounds, sparsity, as_linear_operator, args, kwargs)
    386         f0 = np.atleast_1d(f0)
    387         if f0.ndim > 1:
--> 388             raise ValueError("`f0` passed has more than 1 dimension.")
    389 
    390     if np.any((x0 < lb) | (x0 > ub)):

ValueError: `f0` passed has more than 1 dimension.

**Comment by krasserm** [comment]
Please provide a list of dependency versions you are using.

**Comment by Ethanwl** [comment]
python:3.7.9, numpy:1.19.2, scipy:1.5.2

**Comment by krasserm** [comment]
Here's a quick fix to get this working with newer versions of scipy:

```python
    def nll_naive(theta):
        # Naive implementation of Eq. (7). Works well for the examples 
        # in this article but is numerically less stable compared to 
        # the implementation in nll_stable below.
        K = kernel(X_train, X_train, l=theta[0], sigma_f=theta[1]) + \
            noise**2 * np.eye(len(X_train))
        res = 0.5 * np.log(det(K)) + \
              0.5 * Y_train.T.dot(inv(K).dot(Y_train)) + \
              0.5 * len(X_train) * np.log(2*np.pi)
        return res[0]
```

Problem is that the minimization objective function returns an array of size 1 whereas newer scipy versions require a scalar. I'll push a fix to master later this week. Thanks for reporting!
