### ISSUE TITLE
No module named 'bayesian_optimization_util'

### ISSUE THREAD

**Issue by bhanuexcalibur** [krasserm/bayesian-machine-learning#17]
No module named 'bayesian_optimization_util' is found in the below file ,cell number 8
https://github.com/krasserm/bayesian-machine-learning/blob/dev/bayesian-optimization/bayesian_optimization.ipynb

**Comment by krasserm** [comment]
This module is located in the same directory as the notebook. How did you run the notebook?

**Comment by bhanuexcalibur** [comment]
By opening the file in google colab and running it

**Comment by krasserm** [comment]
Seems you forgot to run the top-most cell in the notebook.

**Comment by krasserm** [comment]
Please re-open if the issue persists
