### ISSUE TITLE
Slow "pymc4.sample" on multi-core CPUs

### ISSUE THREAD

**Issue by GloryyrolG** [krasserm/bayesian-machine-learning#19]
Hi,

When I ran the awesome `bayesian_neural_networks_pymc4.ipynb`, in `Inference` section, the code seems to run slowly. As the tutorial suggests, 

> With the current version of PyMC4, MCMC inference using NUTS on a GPU is quite slow compared to a multi-core CPU (need to investigate that in more detail). To enforce inference on a CPU set environment variable CUDA_VISIBLE_DEVICES to an empty value. There is no progress bar visible yet during sampling but the following shouldn't take longer than a few minutes on a modern multi-core CPU.

But it took a long time when I ran this block, i.e.,

```python
# MCMC inference with NUTS
import os; os.environ['CUDA_VISIBLE_DEVICES']=''  # This line is what I added. It still runs on CPUs without the statement.
trace = pm.sample(model(x, y, prior_scale=3), burn_in=100, num_samples=1000)
```

What is your opinion on it? Thanks.

**Comment by krasserm** [comment]
Don't use PyMC4, [its development has been discontinued](https://pymc-devs.medium.com/the-future-of-pymc3-or-theano-is-dead-long-live-theano-d8005f8a0e9b). PyMC3 on Theano with the new JAX backend is the future.

**Comment by GloryyrolG** [comment]
Thanks for your really instant reply. So can I change the ipynb to use PyMC3 with a few modifications, like,

```python
import pymc4 as pm  # => import pymc3 as pm
```

Or the ipynb is relatively useless? Thanks.

**Comment by krasserm** [comment]
The notebook is relatively useless. A complete rewrite is needed to get this running with PyMC3.
