### ISSUE TITLE
accounting multiple times for the prior loss

### ISSUE THREAD

**Issue by ucohen** [krasserm/bayesian-machine-learning#3]
first, this is a great repo! thanks! 

In the forward pass `log_mixture_prior_prob` is  added each time `kl_loss` is called.
how does it fit with the formulation of the loss, where it should be added once?

**Comment by krasserm** [comment]
Each time `log_mixture_prior_prob` is called it is passed a different subset of weights. It is called twice per layer, once for the kernel weights and once for the bias weights. This is repeated n times for n layers. Equation (3) in the text summarizes all weights of the neural network as vector **w** and the prior as p(**w**). The code decomposes that into a sum of log probabilities. Does that help?
