### ISSUE TITLE
An inconspicuous mistake

### ISSUE THREAD

**Issue by UCAS-BigBird** [krasserm/bayesian-machine-learning#4]
Dear author,
 
I find there have **an inconspicuous mistake**

just as the following

`return np.sum(np.log(np.diagonal(cholesky(K)))) + \
               0.5 * Y_train.T.dot(inv(K).dot(Y_train)) + \
               0.5 * len(X_train) * np.log(2*np.pi)`

This should be changed with respect to the formula
<img width="437" alt="1564391060" src="https://user-images.githubusercontent.com/42146560/62035690-ef019000-b222-11e9-9ae5-eb24b47df54c.png">

 `return  0.5*np.sum(np.log(np.diagonal(cholesky(K)))) + \
               0.5 * Y_train.T.dot(inv(K).dot(Y_train)) + \
               0.5 * len(X_train) * np.log(2*np.pi)`

Regards

**Comment by UCAS-BigBird** [comment]
<img width="504" alt="1564391132(1)" src="https://user-images.githubusercontent.com/42146560/62035792-19534d80-b223-11e9-8d96-309746080e34.png">

**Comment by krasserm** [comment]
The implementation is actually correct. When computing the determinant via Cholesky decomposition the factor `0.5` disappears. For details see http://www.gaussianprocess.org/gpml/chapters/RW2.pdf, Section 2.2, Algorithm 2.1.

On the other hand, I only partially implemented the numerically more stable version as described in the reference above. I therefore [updated the article](https://nbviewer.jupyter.org/github/krasserm/bayesian-machine-learning/blob/master/gaussian_processes.ipynb#Effect-of-kernel-parameters-and-noise-parameter) where I provided a naive implementation that has a 1:1 correspondence with Equation (7)

```python
def step(theta):
    # Naive implementation of Eq. (7). Works well for the examples 
    # in this article but is numerically less stable compared to 
    # the implementation in nll_stable below.
    K = kernel(X_train, X_train, l=theta[0], sigma_f=theta[1]) + \
        noise**2 * np.eye(len(X_train))
    return 0.5 * np.log(det(K)) + \
           0.5 * Y_train.T.dot(inv(K).dot(Y_train)) + \
           0.5 * len(X_train) * np.log(2*np.pi)
```

and a numerically more stable version as described in the reference:

```python
def step(theta):
    # Numerically more stable implementation of Eq. (7) as described
    # in http://www.gaussianprocess.org/gpml/chapters/RW2.pdf, Section
    # 2.2, Algorithm 2.1.
    K = kernel(X_train, X_train, l=theta[0], sigma_f=theta[1]) + \
        noise**2 * np.eye(len(X_train))
    L = cholesky(K)
    return np.sum(np.log(np.diagonal(L))) + \
           0.5 * Y_train.T.dot(lstsq(L.T, lstsq(L, Y_train)[0])[0]) + \
           0.5 * len(X_train) * np.log(2*np.pi)
```

Both give equivalent results which also match the results from 3rd-party libraries as verified in section [Libraries that implement GPs](https://nbviewer.jupyter.org/github/krasserm/bayesian-machine-learning/blob/master/gaussian_processes.ipynb#Libraries-that-implement-GPs). If you only add a factor of `0.5` to the old implementation of `step` you'll get a wrong result and consequently an assertion error in this section.
