### ISSUE TITLE
The parameter kl_loss_weight of the __init__ method of the DenseVariational class is not used

### ISSUE THREAD

**Issue by nbro** [krasserm/bayesian-machine-learning#6]
The parameter `kl_loss_weight` of the `__init__` method of the `DenseVariational` class is not used because, in the notebook (https://github.com/krasserm/bayesian-machine-learning/blob/master/bayesian_neural_networks.ipynb), you're using the global variable `kl_loss_weight` in the `kl_loss` method of the `DenseVariational` rather than using `self.kl_loss_weight`. I suggest you change the `kl_loss` to use  `self.kl_loss_weight` rather than the corresponding global variable.

**Comment by krasserm** [comment]
Good catch, thanks for reporting!
