### ISSUE TITLE
Issue in learning the variance for discontinuous training data

### ISSUE THREAD

**Issue by coolbuddyabdur** [krasserm/bayesian-machine-learning#8]
Thank you very much for your implementation. It's highly helpful.

I'm attempting to learn different functions using the BNN model. I restrict the range of training values to be discontinuous. For example, in an attempt to learn a polynomial function (2*x^2 +2), I slightly change the number of neurons and number of layers for better prediction and train the network with equally sampled values from -4 to -1 and from 1 to 4. When testing the network with equally sampled values from -6 to 6, I would expect the Epistemic uncertainty to be high at the range of values that the network has not seen during the training, i.e from -6 to -4, from -1 to 1 and from 4 to 6. 

Observations after testing:
1, The predicted mean is close to the expected test value in the trained range ([-4,-1], [1,4]) as expected
2, The variance of predicted values in the untrained range ([-6,-4], [4,6]) is high as expected

3, The variance of predicted values in the untrained range ([-1,1]), is lower which is contradictory to the concept of determining epistemic uncertainty through BNN.   Could there be any explanation for this and Is there some way to make the model to have high variance in all the ranges of untrained data? 

![Polynomial function](https://user-images.githubusercontent.com/17695906/68542668-682a8a80-03af-11ea-8259-352503e165c9.png)
  

I have also done trained the exact model you have presented for 'Sin()' function with discontinuous range of training data and have observed the same issue
![Sin_incomplete](https://user-images.githubusercontent.com/17695906/68543086-f2282280-03b2-11ea-8918-20d46961a873.png)

Thanks a lot in advance !!

**Comment by krasserm** [comment]
That's an interesting observation and I have to take a closer look to understand why this is the case. From another experiment I found that the learnable prior might be an issue but I'm not sure. I'd also try to implement it with tensorflow-probability directly and see if there are similar issues. Having other priorities at the moment but will for sure dedicate some time later. Thanks for reporting!

**Comment by krasserm** [comment]
Hi @coolbuddyabdur, first of all, sorry for the late follow-up, hope my findings are still of interest to you. I wrote a [notebook](https://nbviewer.jupyter.org/github/krasserm/bayesian-machine-learning/blob/wip-ncp/ncp/ncp.ipynb) (still a draft) that hopefully sheds some light on the issue you reported. It also demonstrates how [noise contrastive priors](http://proceedings.mlr.press/v115/hafner20a.html) (NCPs) can help to get better uncertainty estimates for neural network predictions. Bayesian neural networks with priors in weight space are sometimes over-confident in regions outside the training data distribution (as you already reported):

![bnn](https://user-images.githubusercontent.com/202907/93662195-9f9da500-fa5e-11ea-91e3-991fdc4ad03f.png)

NCPs are defined in data space which makes it easier to define a prior for out-of-distribution regions, resulting in more reliable uncertainty estimates

![bnn+ncp](https://user-images.githubusercontent.com/202907/93662202-a7f5e000-fa5e-11ea-8d33-d89418c7a2d8.png)

NCPs are only one of many possible ways to get better uncertainty estimates but they are a good fit for this specific example.
